[package]
name = "common_core"
version = "0.1.1"
edition = "2021"

[dependencies]
libc = "0.2.174"
common_err = {path = "../common_err"}
rand = "0.9.2"
backtrace = "0.3.75"
rustc-demangle = "0.1.25"
log = "0.4.22"

[[test]]
name = "test_core"
path = "tests/mod.rs"
