[package]
name = "common_exec_duckdb"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "1.3.0",  features = ["bundled"]}
common_core = {path = "../common_core"}
common_relational_exec = {path = "../common_relational_exec"}