[workspace]
members = ["common_core", "common_err", "common_exec_scylla", "common_exec_pg", "common_exec_duckdb", "common_rs", "common_thread", "common_pair_exec", "common_exec_redis", "common_exec_odbc"]
resolver = "2"
