[package]
name = "common_exec_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
common_core = {path = "../common_core"}
common_relational_exec = {path = "../common_relational_exec"}
common_err = {path = "../common_err"}