[package]
name = "common_exec_scylla"
version = "0.1.0"
edition = "2021"

[dependencies]
common_core = {path = "../common_core"}
common_relational_exec = {path = "../common_relational_exec"}
tokio = {version = "1.43.0"}
scylla = "1.3.1"
